language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  
notifications:
  email:
    - john@operationspark.org
    - max@operationspark.org
  slack: operationspark:ixq1B2YGNVjAZoh3PVEOoHic
  
script: ./.master/pr.sh